CONTIKI_PROJECT = lpcxpresso1347-shell

PROJECTDIRS = $(CONTIKI)/platform/lpcxpresso1347/apps

APPS = serial-shell

PROJECT_SOURCEFILES = shell-at45db.c

all: $(CONTIKI_PROJECT)

CONTIKI = ../../..
include $(CONTIKI)/Makefile.include
