CONTIKI_PROJECT = lpcxpresso1347-shell

#PROJECTDIRS = $(CONTIKI)/platform/mbxxx/apps

APPS = serial-shell

#PROJECT_SOURCEFILES = shell-sensors.c

all: $(CONTIKI_PROJECT)

CONTIKI = ../../..
include $(CONTIKI)/Makefile.include
