LPCXPRESSO1347 =  


CONTIKI_TARGET_DIRS = .

CFLAGS+=-DAUTOSTART_ENABLE

ifndef CONTIKI_TARGET_MAIN
CONTIKI_TARGET_MAIN = contiki-main.c
endif

CONTIKI_TARGET_SOURCEFILES += $(SENSORS) $(CONTIKI_TARGET_MAIN)

# include $(CONTIKI)/platform/$(TARGET)/apps/Makefile.apps

include $(CONTIKI)/cpu/arm/lpc1347/Makefile.lpc1347

#contiki-$(TARGET).a: ${addprefix $(OBJECTDIR)/,symbols.o}

ifndef BASE_IP
BASE_IP := 172.16.1.1
endif

