CONTIKI = ../..

all: example-abc example-collect example-polite \
     example-broadcast example-mesh example-trickle example-rucb \
     example-runicast example-unicast example-neighbors \
     example-rudolph0 example-rudolph2

# needs rtimer
# example-rudolph1

include $(CONTIKI)/Makefile.include
