CONTIKI = ../..

all: example-abc example-collect example-polite \
     example-broadcast \
     example-runicast example-unicast example-neighbors

# example-mesh example-trickle example-rucb   needs button
# example-rudolph0 example-rudolph1 example-rudolph2  needs cfs

include $(CONTIKI)/Makefile.include
